import os
import json
import urllib.request
import requests
from dotenv import load_dotenv

# Ensure env vars are loaded
load_dotenv()

class EmailService:
    def __init__(self):
        self.api_key = os.getenv("RESEND_API_KEY", "")
        self.from_email = os.getenv("FROM_EMAIL", "onboarding@resend.dev") # Default Resend testing email
        self.to_email = os.getenv("TO_EMAIL", "")
        
    def generate_html_report(self, summary_data):
        """Generates a beautiful HTML email from the quiz summary data."""
        pending = summary_data.get("pending", [])
        attempted = summary_data.get("attempted", [])
        upcoming = summary_data.get("upcoming", [])
        
        # HTML template styling
        html = """
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; background-color: #f9f9f9; padding: 20px; }
                .container { max-width: 600px; margin: 0 auto; background: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }
                .header { text-align: center; border-bottom: 2px solid #f0f0f0; padding-bottom: 20px; margin-bottom: 20px; }
                .header h2 { color: #2c3e50; margin: 0; }
                .summary-box { background: #e8f4f8; padding: 15px; border-radius: 6px; margin-bottom: 25px; border-left: 4px solid #3498db; }
                h3 { color: #2c3e50; border-bottom: 1px solid #eee; padding-bottom: 5px; }
                table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 14px; }
                th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
                th { background-color: #f8f9fa; color: #555; }
                .badge-danger { background: #e74c3c; color: white; padding: 3px 8px; border-radius: 12px; font-size: 12px; font-weight: bold; }
                .badge-success { background: #2ecc71; color: white; padding: 3px 8px; border-radius: 12px; font-size: 12px; font-weight: bold; }
                .badge-info { background: #3498db; color: white; padding: 3px 8px; border-radius: 12px; font-size: 12px; font-weight: bold; }
                .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #888; }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h2>📚 VU LMS Quiz Update</h2>
                </div>
                
                <div class="summary-box">
                    <strong>Quick Summary:</strong><br>
                    You have <span class="badge-danger">{pending_count} Pending</span> quizzes, 
                    <span class="badge-success">{attempted_count} Attempted</span> quizzes, and 
                    <span class="badge-info">{upcoming_count} Upcoming</span> quizzes.
                </div>
        """
        
        html = html.replace("{pending_count}", str(len(pending)))
        html = html.replace("{attempted_count}", str(len(attempted)))
        html = html.replace("{upcoming_count}", str(len(upcoming)))
        
        # Helper to generate table rows
        def generate_table(items, empty_msg):
            if not items:
                return f"<p style='color: #777; font-style: italic;'>{empty_msg}</p>"
            
            tbl = "<table><tr><th>Subject</th><th>Title</th><th>Deadline / Info</th></tr>"
            for item in items:
                subject = item.get("subject", "N/A")
                title = item.get("title", "N/A")
                deadline = item.get("end", "N/A")
                if deadline == "N/A":
                    deadline = item.get("start", "N/A")
                    
                tbl += f"<tr><td><strong>{subject}</strong></td><td>{title}</td><td>{deadline}</td></tr>"
            tbl += "</table>"
            return tbl
            
        if pending:
            html += "<h3>🚨 Action Required: Pending Quizzes</h3>"
            html += generate_table(pending, "No pending quizzes. Good job!")
            
        if upcoming:
            html += "<h3>🗓️ Upcoming Quizzes</h3>"
            html += generate_table(upcoming, "No upcoming quizzes.")
            
        if attempted:
            html += "<h3>✅ Recently Attempted / Closed</h3>"
            html += generate_table(attempted, "No recently attempted quizzes.")
            
        html += """
                <div class="footer">
                    This is an automated report generated by your VU Quiz Agent.
                </div>
            </div>
        </body>
        </html>
        """
        return html

    def send_report(self, summary_data):
        if not self.api_key:
            print("   -> ⚠️  Email Notification Skipped: RESEND_API_KEY not found in .env")
            return False
            
        if not self.to_email:
            print("   -> ⚠️  Email Notification Skipped: TO_EMAIL not found in .env")
            return False

        print(f"   -> Preparing HTML email report for {self.to_email}...")
        
        html_content = self.generate_html_report(summary_data)
        
        pending_count = len(summary_data.get("pending", []))
        subject = f"VU LMS Update: {pending_count} Pending Quizzes" if pending_count > 0 else "VU LMS Update: All Caught Up!"
        
        # Prepare Resend API payload and headers
        payload = {
            "from": f"VU Quiz Agent <{self.from_email}>",
            "to": [self.to_email],
            "subject": subject,
            "html": html_content
        }
        
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
        }
        
        try:
            # Clean and simple requests call
            response = requests.post("https://api.resend.com/emails", json=payload, headers=headers)
            
            if response.status_code in [200, 201, 202]:
                print("   -> 📧 Email Sent Successfully via Resend!")
                return True
            else:
                print(f"   -> ❌ Email Sending Failed! Status: {response.status_code}, Details: {response.text}")
                return False
        except Exception as e:
            print(f"   -> ❌ Unexpected error while sending email: {str(e)}")
            return False

# Singleton instance
email_service = EmailService()
